### ISSUE TITLE
Standardize the save format

### ISSUE THREAD

**Issue by Salgat** [Salgat/GameBoyEmulator-GBS#1]
Need to use a standardized save format so that save files from other emulators work with this. Maybe this is helpful.

http://fileformats.archiveteam.org/wiki/GB

**Comment by asalgat** [comment]
So the best bet is to save a raw binary file of $a000-$a1ff (plus RTC data) with no header and the extension .SAV. Add a command line parameter of -save="saveFile.sav" to load a save file, and have a hotkey available for creating save files. 

Be sure to test this .SAV against other common emulators and also loading other common emulator .SAV files in this emulator.

**Comment by Salgat** [comment]
The best way to handle this (I don't want to write to sav every time a save byte is written and I don't want to keep a stream open constantly) is to have a dirty flag for the sav region and update the .SAV file once a second whenever it is dirty.

**Comment by Salgat** [comment]
Implemented with d871c2e6f9203ffb6ef7550f276c6a683add02d2
